language: python
python: "3.8"

install:
    - pip install -r requirements.txt
    
matrix:
  include:
    - python 3.8
    install:
        - pip install -r requirements.txt
    scripts:
   
        - pytest --pylint
    env: test=test
    
        # Build and test new
    - python 3.8
    env: VARIA=true
    script:
        - print ("Hello")
